name: newsapi
description: A library for News API from newsapi.org.
version: 0.1.0
homepage: https://github.com/asimbera/newsapi

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  dio: ^4.0.4
  retrofit: ^3.0.0
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  freezed: ^1.0.0
  retrofit_generator: ^3.0.0+2
  json_serializable: ^6.0.1
